Valid
DaoxingHuang/flutter.cn pull request #1
Opened 2019-10-27 09:05 UTC by DaoxingHuang

1.因为没有移动端的经验和flutter开发经验，部分专业名词可能会存在问题
2.正常情况下，google 出的一些调试工具其实并没有官方汉化，例如 DevTools，不知道清楚CPU profiler是不是，如果也和devtools一样，在涉及界面上的一些选项时，还是需要保留英文，例如Call tree 这个选项，从工具的角度它叫Call tree,但从的角度来说 它应该叫翻译 调用树 或是 跟踪树
3.带表格的翻译没有比较好的样例，唯独一个比较ok的vs-code.md，但还是有点问题 ，请查看[进阶调试]https://flutter.cn/docs/development/tools/vs-code，所以我的理解修改的，目前不知道怎么验证，后续确认再修改
4.第一次翻译，必然存在不足和不对的地方 ，会持续学习、改进和完善

2019-10-27 09:44 UTC, Vadaski requested changes
感谢你的时间！我先 review 了一些格式问题，内容以及专业名词等下再来看看；）

2019-10-27 09:44 UTC, Vadaski commented on src/docs/development/tools/devtools/performance.md
> +
{{site.alert.note}} 之间需要加入换行，样例：
{{site.alert.note}}

  The performance view works with mobile apps only.
  Use Chrome DevTools to [analyze
  performance](https://developers.google.com/web/tools/chrome-devtools/evaluate-performance/)
  of a web app.

  性能视图仅可以运行在手机应用程序中。
  对于web应用程序，请使用Chrome自带的开发者工具进行[性能分析](https://developers.google.com/web/tools/chrome-devtools/evaluate-performance/)
  
{{site.alert.end}}

2019-10-27 09:44 UTC, Vadaski commented on src/docs/development/tools/devtools/performance.md
> +性能视图可以记录并分析Dart应用程序的性能，以帮助我们找到应用程序的性能瓶颈。如果你之前使用过DevTools,那么你应该很快熟悉使用它。
中文与英文之间应该加入空格；）

2019-10-27 09:44 UTC, Vadaski commented on src/docs/development/tools/devtools/performance.md
> +性能视图可以记录并分析Dart应用程序的性能，以帮助我们找到应用程序的性能瓶颈。如果你之前使用过DevTools,那么你应该很快熟悉使用它。
这句话后续的翻译内容是出自哪里呢，我这里看到的原文是 The performance view allows you to record and profile a session from your Dart application

2019-10-27 09:44 UTC, Vadaski commented on src/docs/development/tools/devtools/performance.md
>  {{site.alert.end}}
同上，需要加入换行，中英文间加入空格

2019-10-27 09:44 UTC, Vadaski commented on src/docs/development/tools/devtools/performance.md
> +单击`Record`开始进行记录，完成后点击`Stop`停止记录，分析器会把收集的信息推送到VM并分别在不同的信息窗口进行展示调用树(Call Tree,
译文与原文之间需要加入换行，英文中文之间需要加入空格

2019-10-27 09:44 UTC, Vadaski commented on src/docs/development/tools/devtools/performance.md
> +单击`Record`开始进行记录，完成后点击`Stop`停止记录，分析器会把收集的信息推送到VM并分别在不同的信息窗口进行展示调用树(Call Tree,
括号内的内容如果可以翻译的话，请翻译；）

2019-10-27 09:44 UTC, Vadaski commented on src/docs/development/tools/devtools/performance.md
> +VM收集cpu样本的默认速率为1/250μs(即每250微秒收集一次数据)。
中英文之间添加空格

2019-10-27 09:44 UTC, Vadaski commented on src/docs/development/tools/devtools/performance.md
> +**高粒度**的配置会具有更高效的采样率，因此单元时间内采集的CPU信息会更加详细且采集样例更多。
中英文之间添加空格，以下相同问题麻烦一起改一下，thanks！

2019-10-27 09:44 UTC, Vadaski commented on src/docs/development/tools/devtools/performance.md
> +在这张表中，可以展开一个方法查看他的所有调用过程。
「他」=> 「它」

2019-10-27 09:44 UTC, Vadaski commented on src/docs/development/tools/devtools/performance.md
>  <dt markdown="1">**Total time**</dt>
这里请参考这个格式

2019-10-27 09:44 UTC, Vadaski commented on src/docs/development/tools/devtools/performance.md
>  <dt markdown="1">**Total time**</dt>
<p>
english
</p>

<p>
中文
</p>

2019-10-27 09:44 UTC, Vadaski commented on src/docs/development/tools/devtools/performance.md
>  <dt markdown="1">**Total time**</dt>
https://github.com/cfug/flutter.cn/wiki/Translation-Spec
HTML 内容 - 容器型块元素

2019-10-27 09:44 UTC, Vadaski commented on src/docs/development/tools/devtools/performance.md
>  <dl markdown="1">
同上，请参考 HTML 内容 - 容器型块元素 格式

2019-10-27 10:02 UTC, Vadaski commented
> 1.因为没有移动端的经验和flutter开发经验，部分专业名词可能会存在问题
> 2.正常情况下，google 出的一些调试工具其实并没有官方汉化，例如 DevTools，不知道清楚CPU profiler是不是，如果也和devtools一样，在涉及界面上的一些选项时，还是需要保留英文，例如Call tree 这个选项，从工具的角度它叫Call tree,但从的角度来说 它应该叫翻译 调用树 或是 跟踪树
> 3.带表格的翻译没有比较好的样例，唯独一个比较ok的vs-code.md，但还是有点问题 ，请查看[进阶调试][https://flutter.cn/docs/development/tools/vs-code，所以我的理解修改的，目前不知道怎么验证，后续确认再修改](https://flutter.cn/docs/development/tools/vs-code%EF%BC%8C%E6%89%80%E4%BB%A5%E6%88%91%E7%9A%84%E7%90%86%E8%A7%A3%E4%BF%AE%E6%94%B9%E7%9A%84%EF%BC%8C%E7%9B%AE%E5%89%8D%E4%B8%8D%E7%9F%A5%E9%81%93%E6%80%8E%E4%B9%88%E9%AA%8C%E8%AF%81%EF%BC%8C%E5%90%8E%E7%BB%AD%E7%A1%AE%E8%AE%A4%E5%86%8D%E4%BF%AE%E6%94%B9)
> 4.第一次翻译，必然存在不足和不对的地方 ，会持续学习、改进和完善

1. 专业名词问题这个还需大家斟酌，可以一起探讨。如果是有共识的可以直接使用，如果是新的概念，翻译内容保证「信、达、雅」即可
2.例如 DevTools 这样的专有名词可以不用翻译，具体我们可以 case by case 去处理；）
3.关于表格翻译我刚去查证了一下，需要手动添加 <p> 标签进行处理，刚才我的 review 有误，抱歉！
![image](https://user-images.githubusercontent.com/23734225/67632827-bafe3f80-f8e3-11e9-8adb-715e6661fdac.png)
4.很棒，希望我们都能有所收获，再次感谢你的时间

2019-10-27 10:02 UTC, Vadaski commented
关于表格，需要手动在原文（英文）包裹<p> 标签，同样的，译文也需要包裹 <p> 标签

2019-10-27 15:09 UTC, Vadaski requested changes
还有一些格式问题，麻烦再次修改。
ps. fix 掉了的 review 可以点 resolve ；）

2019-10-27 15:09 UTC, Vadaski commented on src/docs/development/tools/devtools/performance.md
> +   **对于Flutter应用程序，需要使用profile 构建模式才能使用性能分析**
这里中英文之间还需加入空格喔；）

2019-10-27 15:09 UTC, Vadaski commented on src/docs/development/tools/devtools/performance.md
> +单击`Record`开始进行记录，完成后点击`Stop`停止记录，分析器会把收集的信息推送到VM并分别在不同的信息窗口进行展示调用树(Call Tree,
同上，中英文

2019-10-27 15:09 UTC, Vadaski commented on src/docs/development/tools/devtools/performance.md
> +VM 收集 CPU 样本的默认速率为1/250μs(即每250微秒收集一次数据)。
中文和数字之间加入空格

2019-10-27 15:09 UTC, Vadaski commented on src/docs/development/tools/devtools/performance.md
> +VM 收集 CPU 样本的默认速率为1/250μs(即每250微秒收集一次数据)。
同上，中英文

2019-10-27 15:09 UTC, Vadaski commented on src/docs/development/tools/devtools/performance.md
> +**Bottom up**视图也是用于显示方法调用堆栈，但顾名思义，它是一个自下而上的表示方式。
同上，中英文

2019-10-27 15:09 UTC, Vadaski commented on src/docs/development/tools/devtools/performance.md
> +在**Bottom up**调用树中对于最顶层的方法(叶堆栈帧)，它表示执行自己的代码所需要的时间。
同上，中英文

2019-11-01 06:24 UTC, Vadaski commented
@Realank 彦博哥也来看看😊

2019-11-01 17:40 UTC, Vadaski requested changes
cool，译文质量很高。还有几处需要再次修改下，thanks！

2019-11-01 17:40 UTC, Vadaski commented on src/docs/development/tools/devtools/performance.md
>    The performance view works with mobile apps only.
「The performance view works with mobile apps only.」此句根据我的理解原文的意思是，performance view 仅能测量移动应用的性能，而不能测量 web，翻译为「性能视图仅适用于移动应用」怎么样？

2019-11-01 17:40 UTC, Vadaski commented on src/docs/development/tools/devtools/performance.md
> +   **对于Flutter应用程序，需要使用profile 构建模式才能使用性能分析**
这里 profile 前少了一个空格

2019-11-01 17:40 UTC, Vadaski commented on src/docs/development/tools/devtools/performance.md
> +   **对于Flutter应用程序，需要使用profile 构建模式才能使用性能分析**
Flutter 也需要空格

2019-11-01 17:40 UTC, Vadaski commented on src/docs/development/tools/devtools/performance.md
> +单击`Record`开始进行记录，完成后点击`Stop`停止记录，分析器会把收集的信息推送到VM并分别在不同的信息窗口进行展示调用树(Call Tree,
需要添加空格

2019-11-01 17:40 UTC, Vadaski commented on src/docs/development/tools/devtools/performance.md
> +单击`Record`开始进行记录，完成后点击`Stop`停止记录，分析器会把收集的信息推送到VM并分别在不同的信息窗口进行展示调用树(Call Tree,
这句翻译 CPU profile 没有体现出来喔

2019-11-01 17:40 UTC, Vadaski commented on src/docs/development/tools/devtools/performance.md
> +VM 收集 CPU 样本的默认速率为 1/250μs (即每250微秒收集一次数据)。
数字与中文之间需要添加空格

2019-11-01 17:40 UTC, Vadaski commented on src/docs/development/tools/devtools/performance.md
> +    the code for its callees.</p>
这里的 <p> 标签是否应该替换为 <t> ？

2019-11-01 17:40 UTC, Vadaski commented on src/docs/development/tools/devtools/performance.md
> +**Bottom up**视图也是用于显示方法调用堆栈，但顾名思义，它是一个自下而上的表示方式。
这里****用于 markdown加粗，不实际显示，所以英文与中文之间还是需要增加空格

2019-11-01 17:40 UTC, Vadaski commented on src/docs/development/tools/devtools/performance.md
> +    the code for its callees.</p>
/<p> => /<t>

2019-11-01 17:41 UTC, Vadaski commented on src/docs/development/tools/devtools/performance.md
> +    the code for its callees.</p>
\<p> => \<t>

2019-11-02 16:30 UTC, DaoxingHuang commented on src/docs/development/tools/devtools/performance.md
> +    the code for its callees.</p>
这里的标签格式是 Luke Cheng @chenglu提供的，保留了原样。

2019-11-03 03:44 UTC, Vadaski commented on src/docs/development/tools/devtools/performance.md
> +    the code for its callees.</p>
@chenglu cc/

2019-11-03 23:45 UTC, chenglu commented on src/docs/development/tools/devtools/performance.md
> +    the code for its callees.</p>
可以参考这个 https://github.com/cfug/flutter.cn/issues/504#issuecomment-547770263，我们对文档做了双语处理，覆盖了一些常见的中英对应，对于那些尚未支持的中英对应翻译，可以使用 ```<t></t>``` 标签包裹，这里 t 的意思就是 translation。

2019-11-03 23:48 UTC, chenglu commented on src/docs/development/tools/devtools/performance.md
> +  对于 web 应用程序，请使用 Chrome 自带的开发者工具进行[性能分析](https://developers.google.com/web/tools/chrome-devtools/evaluate-performance/)
```suggestion
  对于 web 应用程序，请使用 Chrome 自带的开发者工具进行 [性能分析](https://developers.google.cn/web/tools/chrome-devtools/evaluate-performance/)
```
这里建议将 devsite 的链接换成 .cn 因为它已经在国内可用啦（英文内容保持不变）

2019-11-03 23:49 UTC, chenglu commented on src/docs/development/tools/devtools/performance.md
> +单击`Record`开始进行记录 CPU 信息，完成后点击`Stop`停止记录，CPU 分析器会把收集的信息推送到VM并分别在不同的信息窗口进行展示调用树(Call Tree,
```suggestion
单击 `Record` 开始进行记录 CPU 信息，完成后点击 `Stop` 停止记录，CPU 分析器会把收集的信息推送到VM并分别在不同的信息窗口进行展示调用树 (Call Tree,
```

2019-11-03 23:49 UTC, chenglu commented on src/docs/development/tools/devtools/performance.md
> +一般情况下，`Profile granularity`的默认值为:“medium”。
```suggestion
一般情况下，`Profile granularity` 的默认值为: “medium”。
```

2019-11-03 23:50 UTC, chenglu commented on src/docs/development/tools/devtools/performance.md
> +** Bottom up **视图也是用于显示方法调用堆栈，但顾名思义，它是一个自下而上的表示方式。
```suggestion
**Bottom up** 视图也是用于显示方法调用堆栈，但顾名思义，它是一个自下而上的表示方式。
```

2019-11-03 23:50 UTC, chenglu requested changes
一些小的排版问题已经直接提出 suggestion。
cc/ @Vadaski

2019-11-05 08:47 UTC, merged